### ISSUE TITLE
Convert method FindByDateGroupingAsync to EF Core 3.1

### ISSUE THREAD

**Issue by FabricioMedeiros** [acenelio/workshop-asp-net-core-mvc#1]
Hello, 

the method FindByDateGroupingAsync don't work in .NetCore 3.1 ... how can I do to this works ?

Thanks.

**Comment by renanbernardo** [comment]
Para que o método FindByDateGroupingAsync funcione no Entity Framework Core 3.1, é necessário realizar uma pequena adaptação:

Retorne todos os dados primeiro, sem o GroupBy:

```
var retornoSales = await result
                .Include(x => x.Seller)
                .Include(x => x.Seller.Department)
                .OrderByDescending(x => x.Date)
                .ToListAsync();
```

Realize o agrupamento dos dados no retorno do método: 

`return retornoSales.GroupBy(x => x.Seller.Department).ToList();
`

**Comment by FabricioMedeiros** [comment]
> return retornoSales.GroupBy(x => x.Seller.Department).ToList();

Renan, muito obrigado!

Funcionou perfeitamente :)
